### ISSUE TITLE
ability to make zune software detect android phones and sync to them

### ISSUE THREAD

**Issue by desertrooper** [ZuneDev/ZuneModdingHelper#9]
so i have an old android phone that i use as my mp3 player it runs 2.3 so the play store or web browser or youtube don't work any more
there must be a lot of devices like these so is there any way to make these devices sync with zune software because the other way takes time is slow so could you please add this as a feature

**Comment by yoshiask** [comment]
This is a neat idea, but it's near impossible with our current knowledge and capabilities. Modding the Zune software to change anything related to devices is not something I can consider doing right now.
